version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: tapsdoc
      POSTGRES_PASSWORD: taps1234
      POSTGRES_DB: bsn
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

  maildev:
    image: maildev/maildev
    container_name: mail-dev
    restart: unless-stopped
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "8080:1080"
      - "1025:1025"

  bsn-api:
    build: ./backend
    container_name: bsn-api
    image: book-social/book-social:1.0.0
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    restart: unless-stopped

  bsn-ui:
    build: ./frontend
    container_name: bsn-ui
    image: book-social-ui/book-social-ui:1.0.0
    ports:
      - "8080:80"
      - "4000:4000"
    depends_on:
      - bsn-api

volumes:
  postgres:
  pgadmin: