server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bsn
    username: tapsdoc
    password: taps1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mail:
    host: localhost
    port: 1025
    username: tapsdoc
    password: taps1234
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
    protocol: smtp

application:
  security:
    jwt:
      secret-key: 504a7552deaf290ae8e59574956d984fac6e05b831312288a78ae244b0660d55504a7552deaf290ae8e59574956d984fac6e05b831312288a78ae244b0660d55
      expiration: 86400000
      refresh-token:
        expiration: 604800000

  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
